config/routes.rb
Rails.application.routes.draw do
  resources :facilities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/facility.rb
# TODO two
class Facility < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: %i[ show edit update destroy ]
#  before_action :ensure_frame_response, only: %i[ new edit show ]

  def index
    @facilities = Facility.all
  end

  def show
  end

  def new
    @facility = Facility.new
  end

  def edit
  end

  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
# TODO six 1
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("facilities", 
            partial: "facility", 
            locals: { facility: @facility },
            class: 'fade-in-div'
          )
        end
        format.html { redirect_to facility_url(@facility), notice: "Facility was successfully created." }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @facility.update(facility_params)
# TODO six 2
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace( @facility,
            partial: "facility", 
            locals: { facility: @facility },
            class: 'fade-in-div'
          )
        end
        format.html { redirect_to facility_url(@facility), notice: "Facility was successfully updated." }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1 or /facilities/1.json
  def destroy
    @facility.destroy

    respond_to do |format|
# TODO seven 1
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace( @facility,
          partial: "remove_div", 
          locals: { facility: @facility },
          class: 'fade-in-div'
        )
      end
      format.html { redirect_to facilities_url, notice: "Facility was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def ensure_frame_response
      redirect_to root_path unless turbo_frame_request?
    end

    def set_facility
      @facility = Facility.find(params[:id])
    end

    def facility_params
      params.require(:facility).permit(:name, :description, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_facility.html.erb
<!-- TODO four 2 -->
<div id="<%= dom_id facility %>" class='fade-in-div'>
  <p style="color: green"><%= notice %></p>

  <div class='grid-x grid-padding-x'>
    <div class='cell small-3'>
      Name:<br>
      <%= facility.name %>
    </div>
    <div class='cell small-6'>
      Description:<br>
      <%= facility.description %>
    </div>
    <div class='cell small-2'>
      Capacity:<br>
      <%= facility.capacity %>
    </div>
  </div>

    <div class='grid-x grid-padding-x'>
      <div class='cell small-4'>
        <%= link_to "Show", facility, data: { action: "click->dialog#open", turbo_frame: :modal } %>
      </div>
      <div class='cell small-4 text-center'>
        <%= link_to "Edit", edit_facility_path(facility), data: { action: "click->dialog#open", turbo_frame: :modal } %>
      </div>
      <div class='cell small-4 text-center' data-action="turbo:submit-end->dialog#submitEnd">
        <%= button_to facility_path(facility), method: :delete, data: {turbo_confirm: "Are you sure you want to delete this?"} do %>
          Delete
        <% end %>
      </div>
    </div>
<hr>

</div>

app/views/facilities/_form.html.erb
<%= form_with(model: facility) do |form| %>
  <% if facility.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
        <% facility.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/facilities/_remove_div.html.erb
<!-- TODO seven 2 -->
<div id="<%= dom_id facility %>" class='fade-in-div'>

  <div class='grid-x grid-padding-x'>
    <div class='cell small-12'>
      <br>
  </div>

</div>

app/views/facilities/edit.html.erb
<!-- TODO five 2 submitEnd -->

<%= render 'layouts/turbo_dialog' do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <h1>Editing facility</h1>
    <%= render "form", facility: @facility %>
    <%= link_to "Show", @facility %>
    <%# link_to "Show", facility, data: { action: "click->dialog#open", turbo_frame: :modal } %>
  </div>
<% end %>

app/views/facilities/index.html.erb
<!-- TODO four 1 -->
<p style="color: green"><%= notice %></p>

<div class='grid-x grid-padding-x'>
  <div class='cell small-12 text-center'>
    <h1>Facilities</h1>
  </div>
</div>

<div class='grid-x grid-padding-x'>
  <div class='cell small-11'>
    <div id="facilities">
      <% @facilities.each do |facility| %>
        <div class='grid-x grid-padding-x'>
          <div class='cell small-12'>
            <%= render facility %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class='cell small-1'>
    <%= link_to "New facility", new_facility_path, data: { action: "click->dialog#open", turbo_frame: :modal } %>
  </div>
</div>

app/views/facilities/new.html.erb
<!-- TODO five 1 submitEnd -->

<%= render 'layouts/turbo_dialog' do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <h1>New facility</h1>
    <%= render "form", facility: @facility %>
  </div>
<% end %>

app/views/facilities/show.html.erb
<!-- TODO five 3 -->

<%= render 'layouts/turbo_dialog' do %>
  <p style="color: green"><%= notice %></p>
  <%= render @facility %>
<% end %>

app/views/layouts/_turbo_dialog.html.erb
<!-- TODO three 3 -->
<%= turbo_frame_tag :modal do %>
  <dialog data-controller="dialog" data-action="click->dialog#clickOutside"
          style="z-index: 10;  margin-top: 6rem;  border-radius: 0.375rem;  border-width: 4px;  width: 100%;  @media (min-width: 768px) {   width: 66.666667%;  }">
    <div style="padding: 2rem; ">
<!-- note the yield here -->
      <%= yield %>
    </div>
    <div class='grid-x grid-padding-x'>
      <div class='cell small-12 text-center'>
        <button style="background-color: yellow" data-action="dialog#close">Cancel</button>
      </div>
    </div>
  </dialog>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZexampleModalForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<!-- TODO three 2: tag, data attributes -->
<body data-controller="dialog" data-action="click->dialog#clickOutside">

  <%= turbo_frame_tag :modal %>
  <%= yield %>
</body>
</html>